### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by llamamonium11** [mooziii/colorful#1]
![Screenshot_1](https://user-images.githubusercontent.com/46384480/195646383-626116e7-2b43-4ec8-96c1-d86fdf62a1bf.png)
Get this error when using Pufferfish 1.19.2 Fork.

**Comment by mooziii** [comment]
That's only a warning because the plugin is looking if "Paper" is the software. Plugin should work on Pufferfish

**Comment by llamamonium11** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/46384480/195668055-fcc57efd-4c3b-433c-ab51-39714e72d8db.png)
doesn't work

**Comment by llamamonium11** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/46384480/195668188-f7cfbede-9e96-41ef-a899-61f40571818f.png)
Doesn't work
