### ISSUE TITLE
Anvils

### ISSUE THREAD

**Issue by llamamonium11** [mooziii/colorful#2]
![Screenshot_3](https://user-images.githubusercontent.com/46384480/195668614-2eff4fde-9b1d-4608-9882-834bf3dc20f7.png)
Doesn't work in Anvils but everything does.

**Comment by mooziii** [comment]
![image](https://user-images.githubusercontent.com/63669478/195688773-77347be6-b269-4015-b0ce-fe7d031d5765.png)

Works fine for me, did you check the config? If yes please provide console logs

**Comment by llamamonium11** [comment]
Its enabled in the config but here is a Log: https://mclo.gs/RUxdIDu

**Comment by mooziii** [comment]
Everything seems okay, I tried it with pufferfish and it worked for me. Could you check if this is caused maybe by another plugin? (`PlusEnchants` may change something about anvil logic, idk)

**Comment by mooziii** [comment]
bump
